# Generated by Django 5.0.3 on 2024-04-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
