# Generated by Django 5.0.3 on 2024-04-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_orderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='field',
        ),
    ]
