# Generated by Django 5.0.3 on 2024-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='about_executor',
            field=models.TextField(default=1, verbose_name='Об исполнителе'),
            preserve_default=False,
        ),
    ]
