# Generated by Django 5.0.3 on 2024-04-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0006_orderrequest_about_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='about_executor',
            field=models.TextField(blank=True, null=True, verbose_name='Об исполнителе'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='executor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='freelance.executor', verbose_name='Исполнитель'),
        ),
    ]
