# Generated by Django 5.0.3 on 2024-04-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_alter_orderrequest_about_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_taken',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_taken_at',
        ),
    ]
