# Generated by Django 5.0.3 on 2024-04-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('order_rating', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.userprofile')),
            ],
            options={
                'unique_together': {('order', 'user')},
            },
        ),
    ]
